m_russo_mini_project:
    resource: "@MRussoMiniProjectBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
m_russo_lib:
    resource: "@MRussoLibBundle/Resources/config/routing.yml"
    prefix:   /
