# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        in_memory:
            memory: ~
#    acl:
#        connection: default
#        provider: acl_provider
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
#    providers:
#        userproviders:
#            id: user_provider
#    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
#        MRusso\LibBundle\Service\UserInterface:
#            id: user_md5_encoder
#            algorithm: md5

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
