export_post:
    path:     /export
    defaults: { _controller: MRussoMiniProjectBundle:Index:exportCsv}
_homepage:
    path:     /{page}
    defaults: { _controller: MRussoMiniProjectBundle:Index:index,page:1 }
view_post:
    path:     /post/{id}
    defaults: { _controller: MRussoMiniProjectBundle:Index:view }
